version: 0.2

phases:
  install:
    commands:
      - echo "---- STARTING INSTALL PHASE ----"
      - echo "Installing NPM dependencies..."
      - npm install
      - echo "Installing Angular CLI..."
      - npm install -g @angular/cli
      - echo "---- INSTALL PHASE COMPLETED ----"

  build:
    commands:
      - echo "---- STARTING BUILD PHASE ----"
      - echo "Building the Angular application with production configuration..."
      - ng build --configuration production --delete-output-path
      - echo "Build completed."
      - echo "Contents of dist/browser directory:"
      - ls -al dist/browser
      - echo "---- BUILD PHASE COMPLETED ----"

  post_build:
    commands:
      - echo "---- STARTING POST-BUILD PHASE ----"
      - mkdir -p output
      - echo "Copying build files to output directory..."
      - cp -r dist/browser/* output/
      - echo "Contents of output directory:"
      - ls -al output
      - echo "---- POST-BUILD PHASE COMPLETED ----"

artifacts:
  base-directory: output
  files:
    - '**/*'  # Upload all files from the output directory
  discard-paths: yes  # Discard folder structure, place files directly in S3 bucket root
