version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g @angular/cli

  build:
    commands:
      - ng build --configuration production --delete-output-path

artifacts:
  files:
    - '**/*'
  base-directory: dist/browser
