version: 0.2

phases:
  install:
    commands:
      - npm install  # Using npm install instead of npm ci to take advantage of caching

  build:
    commands:
      - npx ng build --configuration production --delete-output-path

artifacts:
  files:
    - '**/*'
  base-directory: dist/browser

cache:
  paths:
    - 'node_modules/**/*'
    - 'package-lock.json'  # Ensure the lock file is cached to speed up dependency resolution
