version: 0.2

phases:
  install:
    commands:
      - npm ci

  build:
    commands:
      - ng build --configuration production --delete-output-path

artifacts:
  files:
    - '**/*'
  base-directory: dist/browser

cache:
  paths:
    - 'node_modules/**/*'
