version: 0.2

phases:
  install:
    commands:
      - echo "Installing NPM dependencies..."
      - npm install  # Installs project dependencies
      - echo "Installing Angular CLI..."
      - npm install -g @angular/cli  # Installs Angular CLI globally

  build:
    commands:
      - echo "Building the Angular application with production configuration..."
      - ng build --configuration production --delete-output-path  # Builds the app

artifacts:
  base-directory: dist/browser  # Specify the directory where your build artifacts are located
  files:
    - '**/*'  # Include all files from the dist/browser directory
