version: 0.2

phases:
  install:
    commands:
      - npm ci

  build:
    commands:
      - npx ng build --configuration production

artifacts:
  files:
    - '**/*'
  base-directory: dist/browser

cache:
  paths:
    - 'package-lock.json'
